title: Tom Turner Blogs
description: A website containing a series of blogs, written by Tom Turner
footer_text: Copyright 2021 Tom Turner
header_feature_image: ../uploads/pages.jpg
header_text: Fonts and their physiological impacts
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 35px
logo: ../uploads/typography-logo.jpg
favicon: ../uploads/typography_logo_mkx_icon.ico
gridlayout: false
fixednavbar: false
upzoom: true
