title: Tom Turner Blogs
description: A website containing a series of blogs, written by Tom Turner
footer_text: Copyright 2021 Tom Turner
header_feature_image: ../uploads/hero-psychology-in-education-1600.png
header_text: How brands can trigger human emotions through font and colour.
header_text_color: "#000000"
bannerheight: 40vmax
navbarheight: 35px
logo: ../uploads/typography-logo.jpg
favicon: ../uploads/typography_logo_mkx_icon.ico
gridlayout: false
fixednavbar: false
upzoom: true
