title: Tom Turner Blogs
description: A website containing a series of blogs, written by Tom Turner
footer_text: Copyright 2021 Tom Turner
header_feature_image: ../uploads/mike-erskine-b4ad8zsaozk-unsplash.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/typography-logo.jpg
favicon: ../uploads/typography-logo.jpg
gridlayout: false
fixednavbar: false
upzoom: true
